name: Android APK Generator

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni yuklab olish
      uses: actions/checkout@v4

    - name: Java muhitini sozlash (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Gradle-ga ruxsatlarni to'g'rilash
      run: |
        if [ -f gradlew ]; then
          chmod +x gradlew
        else
          echo "gradlew fayli topilmadi!"
        fi

    - name: APK faylni yig'ish (Build)
      run: ./gradlew assembleDebug --no-daemon
